name: E2E, Unit and Integration tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  setup-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js 18.15.0
      uses: actions/setup-node@v3
      with:
        node-version: 18.15.0

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: '6.0'
        mongodb-replica-set: test-rs
        mongodb-port: 27017

    - name: Install backend dependencies
      run: |
        cd backend
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run backend
      run: |
        cd backend
        uvicorn app.app:app --reload &
      env:
        MONGO_CONNECTION_STRING: "mongodb://localhost:27017/"
        JWT_SECRET_KEY: "random_string_here"
        JWT_REFRESH_SECRET_KEY: "secure_long_string_here"

    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install

    - name: Run frontend
      run: | 
        cd frontend
        npm start &

    - name: Run integration tests
      run: |
        cd backend
        pip install pytest pytest-asyncio requests mongomock
        pytest tests/
      env:
        MONGO_CONNECTION_STRING: "mongodb://localhost:27017/"
        JWT_SECRET_KEY: "random_string_here"
        JWT_REFRESH_SECRET_KEY: "secure_long_string_here"

    - name: Run unit tests
      run: |
        cd backend
        pip install pytest pytest-asyncio requests mongomock pytest-mock
        pytest tests2/
      env:
        MONGO_CONNECTION_STRING: "mongodb://localhost:27017/"
        JWT_SECRET_KEY: "random_string_here"
        JWT_REFRESH_SECRET_KEY: "secure_long_string_here"